import type { Metadata } from "next";
import { Hind_Madurai } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import Footer from "@/components/Footer";

const hindi = Hind_Madurai({ weight: ['400', '500', '600', '700'], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Realizze odonto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={hindi.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
